name: dongbaek
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  uuid: ^3.0.6
  flutter_bloc: ^8.0.1
  path: ^1.8.0
  path_provider: ^2.0.9
  drift: ^2.3.0
  shared_preferences: ^2.0.13
  expandable: ^5.0.1
  protobuf: ^2.0.1
  grpc: ^3.1.0
  fixnum: ^1.0.1
  collection: ^1.16.0
  flutter_picker: ^2.0.5
  dartx: ^1.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  sqlite3_flutter_libs: ^0.5.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  drift_dev: ^2.3.3

flutter:
  uses-material-design: true
