name: Publish web app to github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual deployment'

jobs:
  build:
    name: Build web app for github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: arduino/setup-protoc@v2
        with:
          version: '23.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart pub global activate protoc_plugin '<21.0.0'
      - run: ./build_proto.sh build
      - run: flutter pub run build_runner build
      - run: flutter build web --base-href "/dongbaek/"
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/web'

  deploy:
    name: Deploy built test web app
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
